export THEOS_PACKAGE_SCHEME = rootless

include $(THEOS)/makefiles/common.mk

S21Overlap_IPHONEOS_DEPLOYMENT_TARGET = 15.0

TWEAK_NAME = S21Overlap
S21Overlap_FILES = Tweak.xm
S21Overlap_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
